### ISSUE TITLE
Production: Make a live site that can tell you what porn tykfyr is watching 

### ISSUE THREAD

**Issue by Line-Lindholm** [tykfyr/tykfyr#1]
**Is your feature request related to a problem? Please describe.**
As the latest tinder conquest for tykfyr I need some sort of system to identify potential concerns in regards to weird kinks or preferences when it comes to satisfying his medister. Currently, it is problematic that I can't tell what type of porn tykfyr likes to watch and how often he watches it. 

**Describe the solution you'd like**
I would like a simple website to inform me what type of porn tykfyr likes to watch. Ideally, the MVP solution should include the following: 

### Menu

- [ ] **Latest views** 
A list with titles for recently viewed porn videos. The list should be in descending order showing the most recent view at the top. This should include a URL for the videos so that Line can do QA of selected materials. 
- [ ] **Top categories**
A list with top search words/sentences. Could potentially be displayed as a Word Cloud (also known as word collage or tag cloud). See picture for reference. 
![image](https://user-images.githubusercontent.com/114447586/192392802-466d925d-b0e9-4289-9c51-554f35ed800b.png)
- [ ] **Live view status**
A live status that is updated when Tykfyr is watching porn. Should probably be placed on the main page/landing page

**Describe alternatives you've considered**

tykfyr handling the communication flow manually. however, texts may be opened at inappropriate times and it will take away focus from him "getting the job done". So doesn't seem like an ideal or scalable solution. 

**Why should we implement this change**

To improve communication between current and future tinder dates (Line especially). 

**Usage/Adoption metrics**

We should probably track who is visiting the page and when. Maybe implement an alarm when hot chicks are visiting the page (might indicate someone ready for some medisterpølse)

**Stakeholders**

- Line Lindholm 
- Potential future tinder dates 
- Maybe _Madklubben_? Not sure if they would like to be updated on this. But seems like they get updated on other inappropriate stuff. So might be relevant. 

**Rollout plan**

- [ ] To be done by PM

**Additional context**

Future potential feature request could include (but would not be limited to):

**A dashboard with a complete overview of:**
- Amount of videos watched this month
- Number of minutes/hours/days watched
- Average time to ejaculation 
- Ideally, some sort of AI for the girls/potential dates visiting the page suggesting what type of sex/fantasies/kinks tykfyr might be in the mood for

**Comment by Line-Lindholm** [comment]
@tykfyr please review this issue and assign it to yourself

**Comment by tykfyr** [comment]
Hey @QueenLindholm 

Before approving this issue, i have some questions i'd like you to answer.

1. Have we considered the privacy-issue here? Both regarding the tykfyr and for the actors/actresses.

2. As we previously discussed, this sort of integration requires that tykfyr actually signs up for the porn-websites he's using. This could result in massive spam in the inbox for him.

3. Due to the fact that porn can be watched from multiple devices (rarely at once tho), we need to implement this feature on all devices. Have this been considered? Bear in mind, that this could extend the timeframe for this feature.

4. We might also run into some copyright related issues.

If you have any questions regarding these questions, please feel free to reach out.

**Comment by Line-Lindholm** [comment]
Hi @tykfyr 

Thank you for your inputs - all very valid points. 

First of, 

> Have we considered the privacy-issue here? Both regarding the tykfyr and for the actors/actresses.

We have, but we decided that since tykfyr is so openly active on all his other SoMe platforms like Twitter and Snapchat he should be willing to sign a consent form. I am working on getting that done and will post it here once signed. 

> As we previously discussed, this sort of integration requires that tykfyr actually signs up for the porn-websites he's using. This could result in massive spam in the inbox for him.

Yes we are aware of that. We have implemented an improved spam filter for his inbox. If that doesn't cut it we might look at other solutions like using a secondary email for this sole purpose- already created one just in case. Then tykfyr will have to create a user with the following email: tykfyr@jerkingoff.com

> Due to the fact that porn can be watched from multiple devices (rarely at once tho), we need to implement this feature on all devices. Have this been considered? Bear in mind, that this could extend the timeframe for this feature.

Since the landing page is not for tykfyr himself this shouldn't be a problem. We have made a questionnaire with a 100% completion rate and that showed us that tykfyr is watching porn on this mobile device 96% of the time. The remaining 4% we can look into at a later time. But I guess we'll cross that bridge when we get there. 

> We might also run into some copyright related issues.

True. We have considered pursuing partnerships with some of the porn sites. This might require a kickback fee but that's okay. @QueenLindholm has enough funding for now so we won't run out of money in the nearest future.

**Comment by Line-Lindholm** [comment]
@tykfyr how much work would it be to build a subscription feature that could notify people on text/emails when tykfyr begins a new video? We recently received a request for this feature and from our initial user research, it seems like it actually solved a pretty big pain for the women involved with tykfyr. The women can use it as a "warning" before they decide to open a snap from him. If they receive the notification beforehand they are aware that the snap could and probably will contain some raw medisterpølse

**Comment by Line-Lindholm** [comment]
@tykfyr have you and the team reviewed this? I see you added the label for good first issue. Will you have any junior developers work on this? They need to be +21 years old as some of the stuff Tykfyr watches is kind of kinky

**Comment by tykfyr** [comment]
Salaam @QueenLindholm 

Unfortunately, due to the lack of resources in the development team, we're gonna need to review the deadlines for this project. No devs are available for atm.

As a plaster on the sår, we could create a common login on the adult sites in question and then you'll be able to see everything.

Let me know what you think.

**Comment by Line-Lindholm** [comment]
@tykfyr well, it seems like the best possible solution at the moment. As a PM I understand that priorities and resources are assigned to other interesting projects at the moment. I'll close this issue and we can get back to it if still relevant later on.
